export function helpText(): string {
  return [
    '',
    '  kairos-trade — adaptive tick-based auto-trading CLI for Deriv synthetic indices',
    '',
    '  Usage:',
    '    kairos-trade [options]',
    '',
    '  Launch options set session defaults. The bot does not auto-start —',
    '  use the /start slash command inside the REPL.',
    '',
    '  Token (required before /start):',
    '    --token <PAT>           Deriv Personal Access Token (or env KAIROS_TRADE_TOKEN)',
    '                            Scopes: Read, Trade, Trading Information, Payments',
    '',
    '  Session defaults:',
    '    --symbol <sym>          Market symbol (default: 1HZ100V — Volatility 100 1s)',
    '    --stake <n>             Stake per trade in account currency (default: 0.35)',
    '    --duration <ticks>      Contract duration in ticks (default: 5)',
    '    --sensitivity <lvl>     low | medium | high | elite (default: medium)',
    '    --min-strength <1-3>    Minimum signal strength to trade (default: 2)',
    '    --max-concurrent <n>    Max open trades at once (default: 1)',
    '    --dry-run               Simulate trades off the live tick stream',
    '    --adaptive <on|off>     Per-signal duration from features (default: on)',
    '                            When on, --duration is the upper cap, not the fixed hold.',
    '    --cooldown <ticks>      Suppress signals for N ticks after a fire (default: 3)',
    '',
    '  Martingale (loss-recovery stake scaling, armed by default after 2 losses):',
    '    --mg <off|classic>      Mode (default: classic)',
    '    --mg-mult <x>           Stake multiplier after a loss (>1, default: 2.2)',
    '    --mg-max-steps <n>      Cap on consecutive armed steps (default: 8)',
    '    --mg-arm-after <n>      Arm only after N consecutive losses (0=always, default: 2)',
    '    --mg-max-stake <n|off>  Per-trade stake cap (default: off)',
    '    --mg-stop-loss <n|off>  Session cumulative loss cap, stops bot (default: 200)',
    '    --mg-take-profit <n|off>Session cumulative profit cap, stops bot (default: off)',
    '    --mg-on-cap <r|p|s>     reset | pause | stop when a cap is hit (default: reset)',
    '',
    '  Connection:',
    '    --app-id <id>           Deriv app ID (default provided; env KAIROS_TRADE_APP_ID)',
    '    --account-id <id>       Pick a specific account (env KAIROS_TRADE_ACCOUNT_ID)',
    '                            If unset, defaults to the first active DEMO account.',
    '                            Run /accounts inside the REPL to list yours.',
    '',
    '  Other:',
    '    --help, -h              Show this help',
    '    --version, -v           Show version',
    '',
    '  Slash commands (inside the REPL):',
    '    /start /stop /pause /resume /status',
    '    /symbol /stake /duration /sensitivity /minstrength /maxconcurrent /dryrun',
    '    /adaptive /cooldown',
    '    /martingale (alias /mg) — see /mg help',
    '    /rotate /pool /fuzzduration',
    '    /sniper — simulate trades, fire real only after N sim losses',
    '    /clear /help /quit',
    '    (Tab completes, up/down for history and menu nav, Ctrl+C quits)',
    '',
    '  Example:',
    '    kairos-trade --token YOUR_PAT --symbol 1HZ100V --dry-run',
    '    > /start',
    '    > /sensitivity high',
    '',
  ].join('\n');
}
